package org.firstinspires.ftc.teamcode.opmodes.auto;

import com.pedropathing.ivy.Command;
import com.pedropathing.math.Pose;

import org.firstinspires.ftc.teamcode.autokit.AutoKit;
import org.firstinspires.ftc.teamcode.autokit.AutoRegistry;
import org.firstinspires.ftc.teamcode.controls.Display;
import org.firstinspires.ftc.teamcode.opmodes.RobotOpMode;
import org.firstinspires.ftc.teamcode.util.Alliance;

import java.util.function.BiFunction;
import java.util.function.Function;

/**
 * Runs an Autonomous generated by the Auto Builder. Each generated Auto gets a five-line OpMode:
 *
 * <pre>
 * &#64;Autonomous(name = "Auto: Hive Rush", group = "Auto")
 * public class HiveRushOpMode extends BuiltAuto {
 *     public HiveRushOpMode() {
 *         super(HiveRushAuto.ACTIONS, HiveRushAuto.CONDITIONS, HiveRushAuto.DRAWN_FOR,
 *                 HiveRushAuto::startPose, HiveRushAuto::build);
 *     }
 * }
 * </pre>
 *
 * <p>At INIT it checks every name the Auto uses against {@link AutoRegistration} and builds the
 * path follower, so a missing mechanism or an untuned robot stops it there, with the reason. At
 * PLAY it mirrors the Auto if the alliance is not the one it was drawn for, sets the start pose and
 * starts. It never guesses an alliance: with none chosen it does not move.
 */
public abstract class BuiltAuto extends RobotOpMode {

    private static final int TRACE_LINES = 4;

    private final String[] actions;
    private final String[] conditions;
    private final String drawnFor;
    private final Function<Boolean, Pose> startPose;
    private final BiFunction<AutoKit, Boolean, Command> build;

    private AutoRegistry registry;
    private long startNs;
    private String problem;
    private final String[] trace = new String[TRACE_LINES];
    private int traceCount;

    protected BuiltAuto(String[] actions, String[] conditions, String drawnFor,
                        Function<Boolean, Pose> startPose, BiFunction<AutoKit, Boolean, Command> build) {
        this.actions = actions;
        this.conditions = conditions;
        this.drawnFor = drawnFor;
        this.startPose = startPose;
        this.build = build;
    }

    @Override
    protected void onInit() {
        registry = AutoRegistration.forRobot(robot, setup);
        registry.requireAll(actions, conditions);
        robot.drive.preparePathFollowing();
    }

    @Override
    protected void onInitLoop() {
        display.line("Drawn for " + drawnFor + "; the other alliance runs it mirrored.");
    }

    @Override
    protected void onStart() {
        Alliance alliance = setup.alliance();
        if (alliance == Alliance.UNKNOWN) {
            problem = "No alliance chosen before PLAY (X = blue, B = red during INIT). Not moving.";
            return;
        }
        boolean mirrored = !alliance.name().equals(drawnFor);
        robot.drive.setPose(startPose.apply(mirrored));
        startNs = System.nanoTime();
        AutoKit kit = new AutoKit(robot.drive, registry, () -> (System.nanoTime() - startNs) / 1e9)
                .trace(this::remember);
        build.apply(kit, mirrored).schedule();
    }

    @Override
    protected void onLoop() {
        if (problem != null) {
            display.status("Auto", Display.Level.FAULT, problem);
            return;
        }
        for (int i = Math.max(0, traceCount - TRACE_LINES); i < traceCount; i++) {
            display.line(trace[i % TRACE_LINES]);
        }
    }

    /** Keeps the last few trace lines for the Match page. */
    private void remember(String line) {
        trace[traceCount % TRACE_LINES] = line;
        traceCount++;
    }
}
