package org.firstinspires.ftc.teamcode.opmodes;

import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import org.junit.Test;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Every Auto generated by the Visualizer has its {@code .pp} source committed in
 * {@code TeamCode/autos/}, under the name its {@code SOURCE} constant gives.
 *
 * <p>The {@code .pp} is the source and the Java is regenerated from it, so a generated class
 * without its file cannot be reviewed as a path, reopened in the Visualizer, or regenerated. See
 * {@code TeamCode/autos/README.md}.
 *
 * <p>A textual source scan, like {@code LoopContractTest}. Every class in
 * {@code opmodes/auto/generated} must declare {@code SOURCE}; any other class that declares one is
 * checked the same way. Before the first generated Auto exists there is nothing to check.
 */
public class AutoSourcesTest {

    private static final Pattern SOURCE =
            Pattern.compile("static\\s+final\\s+String\\s+SOURCE\\s*=\\s*\"([^\"]*)\"");

    @Test
    public void everyGeneratedAutoHasItsPpFileCommitted() {
        File mainJava = mainJavaDirectory();
        File teamCode = mainJava.getParentFile().getParentFile().getParentFile();
        File autos = new File(teamCode, "autos");
        assertTrue("TeamCode/autos/ is missing; it holds the Auto sources (see its README.md)",
                autos.isDirectory());

        List<String> violations = new ArrayList<>();
        for (File file : javaSources(mainJava)) {
            boolean generated = file.getParentFile().getName().equals("generated")
                    && file.getParentFile().getParentFile().getName().equals("auto");
            Matcher source = SOURCE.matcher(read(file));
            if (!source.find()) {
                if (generated) {
                    violations.add(file.getName() + " is a generated Auto without a SOURCE"
                            + " constant — regenerate it with the Visualizer's Export Auto (Java)");
                }
                continue;
            }
            String name = source.group(1);
            if (!name.endsWith(".pp") || name.contains("/") || name.contains("\\")) {
                violations.add(file.getName() + ": SOURCE \"" + name
                        + "\" should be a plain .pp file name");
            } else if (!new File(autos, name).isFile()) {
                violations.add(file.getName() + " was generated from " + name
                        + ", which is not in TeamCode/autos/ — commit it in the same PR");
            }
        }
        if (!violations.isEmpty()) {
            fail(String.join("\n", violations));
        }
    }

    // -------------------------------------------------------------- helpers

    private static List<File> javaSources(File directory) {
        List<File> sources = new ArrayList<>();
        collectJava(directory, sources);
        return sources;
    }

    private static void collectJava(File directory, List<File> into) {
        File[] entries = directory.listFiles();
        if (entries == null) {
            return;
        }
        for (File entry : entries) {
            if (entry.isDirectory()) {
                collectJava(entry, into);
            } else if (entry.getName().endsWith(".java")) {
                into.add(entry);
            }
        }
    }

    private static String read(File file) {
        try {
            return new String(Files.readAllBytes(file.toPath()), StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new AssertionError("Could not read " + file, e);
        }
    }

    /** Same lookup as {@code LoopContractTest}: module dir under Gradle, repo root in an IDE. */
    private static File mainJavaDirectory() {
        File candidate = new File(System.getProperty("user.dir"));
        for (int depth = 0; depth < 4 && candidate != null; depth++) {
            File direct = new File(candidate, "src/main/java");
            if (direct.isDirectory()) {
                return direct.getAbsoluteFile();
            }
            File viaModule = new File(candidate, "TeamCode/src/main/java");
            if (viaModule.isDirectory()) {
                return viaModule.getAbsoluteFile();
            }
            candidate = candidate.getParentFile();
        }
        throw new AssertionError(
                "Could not locate src/main/java from " + System.getProperty("user.dir"));
    }
}
